### PR TITLE
Write batch record for all renderer applications

### PR DESCRIPTION
**Pull request by samfrench**
## Problem
At the moment, we only write a batch record to DynamoDB for renderer applications which have more than one component. This means the PAL can't request this component using a batch request.

## Solution
It seems a better approach, if we write a batch record for all renderer applications, then the PAL (or whatever is going to request the components) can decide if it is going to request them in batch or not.

https://jira.dev.bbc.co.uk/browse/CONNPOL-2834

### CODE REVIEW

**Comment by samfrench** [comment]
@Integralist, this is following on from our discussion yesterday.

@zygotic99, any issues if we write a batch record for one-component renderer applications? I could only think of performance, but it should be miniscule.

**Comment by Integralist** [comment]
Hi @samfrench - thinking about this now (yesterday I spent a fair amount of time diving into the framework code base has this has subsequently given me a much better understanding of this portion of the code): why would anyone make a request to the `components/batch` endpoint if they know they're only requesting a single component? /cc @zygotic99

**Comment by samfrench** [comment]
@Integralist, we discussed this at the Election 2016 working group and decided it would be good to merge this, if the work was already done.

There isn't much benefit in requesting one component through the batch endpoint, but it would be good if we could request all components this way, so we don't have to work out how many components are generated from a particular queue, when adding the components to a page.

**Comment by Integralist** [comment]
If that's the case, then I would prefer the naming of `batch` to be changed because (unless I'm mistaken) it has no real meaning any more in the context of the publisher?

Ultimately, what you're suggesting is that for every single queue message we will:

1. store a key of `<renderer>/<hash>` and give it the value of the version number extracted from the queue message

2. loop each component, and for each iteration we: store the rendered content into S3, then update the lookup table with a key of `<component>/<hash>/<version>` and a value of the S3 location, then update the sequencer table with a key of `<component>/<hash>` and a value of the version number extracted from the queue message 

Neither of those steps need to know anything about 'batching' as a concept, because all they're doing is looping over the files in the model directory. 

So I'd suggest making the following modification...

```rb
def run!
  seq_for(config[:renderer_id]).validate(message, &process_components)
end
```

This eliminates any reference to batching and renames the proc/block to be a little more descriptive (i.e. changing it from `perform` to `process_components`).

**Comment by samfrench** [comment]
@Integralist, I have implemented your suggestion here, by removing the batch reference. Can I get a final check of this please?

**Comment by Integralist** [comment]
@samfrench code looks fine, but there appears to be a conflict ^^

**Comment by samfrench** [comment]
@Integralist, I fixed the conflict with this PR. Someone had renamed a few things...

**Comment by Integralist** [comment]
Yup @samfrench that was Rubocop changes we needed to make in order to get our Jenkins job to pass without issue.

Ps, looks like Travis CI is failing

**Comment by samfrench** [comment]
@Integralist, Travis CI is passing on this now.

**Comment by BBCMarkMcDonnell** [comment]
:+1: / :cake: seems OK to me

**Comment by samfrench** [comment]
Thank you for the review of this one @Integralist. At the moment the version is: "2.0.1". I was thinking of bumping to "2.1.0" before releasing this. Are you happy with the proposed version?

**Comment by Integralist** [comment]
@samfrench I would recommend a patch release

**Pull request merged**
